local function helpNotifcation(text)
    SetNotificationTextEntry("STRING")
    AddTextComponentString(text)
    DrawNotification(false, false)
end

RegisterCommand("rpm", function(source, args, rawCommand)
    print('test')
    TriggerServerEvent("foltone_ticket:getTickets")
    TriggerEvent("foltone_ticket:openMenu")
end, false)

RegisterNetEvent("foltone_ticket:setPlayerCoords")
AddEventHandler("foltone_ticket:setPlayerCoords", function(coords)
    SetEntityCoords(PlayerPedId(), coords)
end)

RegisterNetEvent("foltone_ticket:clientNotify")
AddEventHandler("foltone_ticket:clientNotify", function(text)
    helpNotifcation(text)
end)

RegisterNetEvent("foltone_ticket:revivePlayer")
AddEventHandler("foltone_ticket:revivePlayer", function()
    local playerPed = PlayerPedId()
    print("Revive player")
    helpNotifcation("Player revived")
    StopScreenEffect('DeathFailOut')
end)

RegisterNetEvent("foltone_ticket:healPlayer")
AddEventHandler("foltone_ticket:healPlayer", function()
    local playerPed = PlayerPedId()
    print("Heal player")
    helpNotifcation("Player healed")
    SetEntityHealth(playerPed, 200)
end)

RegisterNetEvent("foltone_ticket:armorPlayer")
AddEventHandler("foltone_ticket:armorPlayer", function()
    local playerPed = PlayerPedId()
    print("Armor player")
    helpNotifcation("Player armored")
    SetPedArmour(playerPed, 100)
end)

RegisterNetEvent("foltone_ticket:killPlayer")
AddEventHandler("foltone_ticket:killPlayer", function()
    local playerPed = PlayerPedId()
    print("Kill player")
    helpNotifcation("Player killed")
    SetEntityHealth(playerPed, 0)
end)

RegisterNetEvent("foltone_ticket:freezePlayer")
AddEventHandler("foltone_ticket:freezePlayer", function()
    local playerPed = PlayerPedId()
    print("Freeze player")
    helpNotifcation("Player frozen")
    FreezeEntityPosition(playerPed, true)
end)

RegisterNetEvent("foltone_ticket:unfreezePlayer")
AddEventHandler("foltone_ticket:unfreezePlayer", function()
    local playerPed = PlayerPedId()
    print("Unfreeze player")
    helpNotifcation("Player unfrozen")
    FreezeEntityPosition(playerPed, false)
end)
